phrase:
  access_token: eae2d62043209662fa2d06303e29a37567412aa6f72f7fd704a9154acef51591
  project_id: 872e72d4904023acee437bc424c08241
  push:
    sources:
    - file: ./en-us.json
      params:
        file_format: simple_json
  pull:
    targets:
    - file: ./<locale_name>.json
      params:
        file_format: simple_json
