phrase:
  access_token: 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
  project_id: d6aaacf925e513af5bfea4c84f6a0402
  push:
    sources:
    - file: ./Adventure_ja.json
      params:
        locale_id: ja
        file_format: simple_json
  pull:
    targets:
    - file: ./Adventure_<locale_name>.json
      params:
        file_format: simple_json
