phrase:
  access_token: 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
  project_id: d6aaacf925e513af5bfea4c84f6a0402
  push:
    sources:
    - file: ./Adventure_ja.json
      params:
        locale_id: ja
        file_format: simple_json
  pull:
    targets:
    - file: ./Adventure_<locale_name>.json
      params:
        file_format: simple_json
