phrase:
  access_token: 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
  project_id: 872e72d4904023acee437bc424c08241
  push:
    sources:
    - file: ./Book Store_en-US.json
      params:
        locale_id: en-US
        file_format: simple_json
  pull:
    targets:
    - file: ./Book Store_<locale_name>.json
      params:
        file_format: simple_json
